apiVersion: v1
appVersion: "1.0"
description: A Nginx chart for Kubernetes
name: nginx
version: 0.1.0
icon: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwihzpSz1trfAhVEc3AKHQPhCAcQjRx6BAgBEAU&url=https%3A%2F%2Flinuxscriptshub.com%2Fssl-https-certification-for-nginx-web-server-from-cloudflare-for-free%2F&psig=AOvVaw2lYwKXgMue6N2GOuXihvP2&ust=1546916289051177
